# Generated by Django 4.1 on 2023-02-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('date_tour', models.DateField()),
            ],
        ),
    ]
