# Generated by Django 4.1 on 2023-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dp', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tour',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
