# Generated by Django 4.1 on 2023-02-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
