# Generated by Django 4.1 on 2023-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tour_date_tour_alter_tour_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_tour',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
