# Generated by Django 4.1 on 2023-02-26 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_alter_tour_date_tour_alter_tour_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_tour',
            field=models.DateField(default=datetime.datetime(2023, 2, 26, 11, 58, 54, 993236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
