# Generated by Django 4.1 on 2023-02-26 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_tour_date_tour_alter_tour_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_tour',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
