# Generated by Django 4.1 on 2023-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_alter_tour_date_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
