# Generated by Django 4.1 on 2023-02-27 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0011_tour_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='users',
            field=models.ManyToManyField(related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
