# Generated by Django 4.1 on 2023-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_alter_tour_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
