# Generated by Django 4.1 on 2023-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_type',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
